### ISSUE TITLE
Cannot Load CalendarActivity after quitting ScheduleActivity or MemoEditActivity

### ISSUE THREAD

**Issue by lhwdev2008** [AppDevelopers2021/androidStudia#7]
Cannot Load CalendarActivity after quitting ScheduleActivity or MemoEditActivity

**Comment by lee-jongwoo** [comment]
I saw some variable declaration issues before. Please check if all variables are declared, especially in the `if` statement.

I’ll have a look on it tomorrow.

**Comment by lhwdev2008** [comment]
> I saw some variable declaration issues before. Please check if all variables are declared, especially in the `if` statement.
> 
> I’ll have a look on it tomorrow.

근데 왜 우리 영어로 대화하냐?

**Comment by lee-jongwoo** [comment]
The issue was caused by incorrect parsing of the `firebaseDate` value.
Now solved
